apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment #atales <--cambie por el nombre de el del deployment base
spec:
  template:
    spec:
      containers:
        - name: atales
          image: rociomagnoni/atales-backend:dev-16973c5

