# overlays/prod/kustomization.yaml
namespace: ambiente-atales-prod


resources:
  - ../../base

patchesStrategicMerge:
  - patch-backend-deployment.yaml
  - patch-frontend-deployment.yaml
  - patch-secret.yaml
  - patch-configmap.yaml
