apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 6
  template:
    spec:
      containers:
        - name: backend
          image: rociomagnoni/atales-backend:prod-44cb11b

