# overlays/dev/kustomization.yaml
#namespace: ambiente-test-prueba
#para el ingress
namePrefix: stg-

resources:
  - ../../base

patchesStrategicMerge:
  - patch-backend-deployment.yaml
  - patch-frontend-deployment.yaml
  - patch-ingress.yaml
