# overlays/dev/kustomization.yaml


namespace: ambiente-atale-stg


resources:
  - ../../base

patchesStrategicMerge:
  - patch-backend-deployment.yaml
  - patch-frontend-deployment.yaml
  - patch-secret.yaml
  - patch-configmap.yaml
